### PR TITLE
Ubuntu Xenial Support on Puppet 4.1

### LINKED ISSUE #298: ubuntu 16.04 not supported
Looks like the version check doesn't like the current ubuntu LTS distro:

```
Error: Unsupported Debian release: 'xenial' at /etc/puppet/modules/graphite/manifests/params.pp:97 on node my.example.com
```

### PR DESCRIPTION
**Pull request by Ajedi32**
Fixes #298

This is my attempt at getting this module working on Ubuntu Xenial. Tested and confirmed to work on Ubuntu Xenial with Puppet 4.8 installed.

Note that due to some issues with pip >=7.0 (which is the version of pip shipped with Ubuntu Xenial) this fix requires support for using the install_options parameter with the package resource using the pip provider. As this feature is only available in Puppet >=4.1, this fix will only work if you have that version of Puppet installed. (See 71251c92c8a1b85b7eb1515a009b7808756c7bee.)

Ubuntu Xenial's package repos only contain Puppet 3.8, so this patch will unfortunately not work out-of-the-box. For installations using Puppet 4.1+ though, it will work fine.

### CODE REVIEW

**Comment by Ajedi32** [comment]
Note that this _is_ currently working for me, but I'm using it in conjunction with a separate module that downgrades pip to 6.1.1 in order to work around graphite-project/graphite-web#1508. Ideally we should get this working properly with the default pip package for Xenial before merging.

**Comment by Ajedi32** [comment]
Rebased to remove dependence on #308 (which is now merged).

**Comment by GhostLyrics** [comment]
Same-ish issue as in my tests.

```plain
vagrant@vagrant:~$ sudo puppet apply -v -e "class {'graphite':}"
Info: Loading facts
Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
Notice: Compiled catalog for vagrant.vm in environment production in 0.49 seconds
Info: Applying configuration version '1479730507'
Notice: /Stage[main]/Graphite::Config_apache/File[/tmp/fix-graphite-race-condition.py]/ensure: defined content as '{md5}e68353ac472d89b28d6488974087b518'
Notice: /Stage[main]/Graphite::Install/Package[python-sqlite]/ensure: ensure changed 'purged' to 'present'
Notice: /Stage[main]/Graphite::Install/Package[python-pip]/ensure: ensure changed 'purged' to 'present'
Notice: /Stage[main]/Graphite::Install/Package[python-memcache]/ensure: ensure changed 'purged' to 'present'
Notice: /Stage[main]/Graphite::Install/Package[python-simplejson]/ensure: ensure changed 'purged' to 'present'
Notice: /Stage[main]/Graphite::Install/Package[python-mysqldb]/ensure: ensure changed 'purged' to 'present'
Notice: /Stage[main]/Graphite::Install/Package[python-tz]/ensure: ensure changed 'purged' to 'present'
Notice: /Stage[main]/Graphite::Install/Package[python-cairo]/ensure: ensure changed 'purged' to 'present'
Notice: /Stage[main]/Graphite::Config_apache/Package[apache2]/ensure: ensure changed 'purged' to 'present'
Notice: /Stage[main]/Graphite::Config_apache/File[/var/log/apache2/graphite-web]/ensure: created
Notice: /Stage[main]/Graphite::Install/Package[python-ldap]/ensure: ensure changed 'purged' to 'present'
Notice: /Stage[main]/Graphite::Install/Package[python-psycopg2]/ensure: ensure changed 'purged' to 'present'
Notice: /Stage[main]/Graphite::Install/Package[graphite-web]/ensure: created
Notice: /Stage[main]/Graphite::Install/Package[twisted]/ensure: created
Notice: /Stage[main]/Graphite::Install/Package[txamqp]/ensure: created
Notice: /Stage[main]/Graphite::Install/Package[django-tagging]/ensure: created
Notice: /Stage[main]/Graphite::Install/Package[whisper]/ensure: created
Notice: /Stage[main]/Graphite::Install/Package[carbon]/ensure: created
Notice: /Stage[main]/Graphite::Install/File[carbon_hack]/ensure: created
Notice: /Stage[main]/Graphite::Install/Package[Django]/ensure: created
Notice: /Stage[main]/Graphite::Install/File[gweb_hack]/ensure: created
Info: Class[Graphite::Install]: Scheduling refresh of Class[Graphite::Config]
Info: Class[Graphite::Install]: Scheduling refresh of Exec[Initial django db creation]
Info: Class[Graphite::Config]: Scheduling refresh of Exec[graphite-reload-systemd]
Info: Class[Graphite::Config]: Scheduling refresh of Exec[Initial django db creation]
Info: Class[Graphite::Config]: Scheduling refresh of Service[carbon-cache]
Notice: /Stage[main]/Graphite::Config/File[/opt/graphite]/ensure: created
Error: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /opt/graphite/conf/storage-schemas.conf20161121-3157-12p5jy4.lock at 281:/etc/puppet/modules/graphite/manifests/config.pp
Error: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /opt/graphite/conf/storage-schemas.conf20161121-3157-12p5jy4.lock at 281:/etc/puppet/modules/graphite/manifests/config.pp
Wrapped exception:
No such file or directory @ dir_s_rmdir - /opt/graphite/conf/storage-schemas.conf20161121-3157-12p5jy4.lock
Error: /Stage[main]/Graphite::Config/File[/opt/graphite/conf/storage-schemas.conf]/ensure: change from absent to file failed: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /opt/graphite/conf/storage-schemas.conf20161121-3157-12p5jy4.lock at 281:/etc/puppet/modules/graphite/manifests/config.pp
Error: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /opt/graphite/conf/graphite_wsgi.py20161121-3157-1u1kw5s.lock at 195:/etc/puppet/modules/graphite/manifests/config.pp
Error: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /opt/graphite/conf/graphite_wsgi.py20161121-3157-1u1kw5s.lock at 195:/etc/puppet/modules/graphite/manifests/config.pp
Wrapped exception:
No such file or directory @ dir_s_rmdir - /opt/graphite/conf/graphite_wsgi.py20161121-3157-1u1kw5s.lock
Error: /Stage[main]/Graphite::Config/File[/opt/graphite/conf/graphite_wsgi.py]/ensure: change from absent to file failed: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /opt/graphite/conf/graphite_wsgi.py20161121-3157-1u1kw5s.lock at 195:/etc/puppet/modules/graphite/manifests/config.pp
Error: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /opt/graphite/conf/carbon.conf20161121-3157-l68z6k.lock at 281:/etc/puppet/modules/graphite/manifests/config.pp
Error: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /opt/graphite/conf/carbon.conf20161121-3157-l68z6k.lock at 281:/etc/puppet/modules/graphite/manifests/config.pp
Wrapped exception:
No such file or directory @ dir_s_rmdir - /opt/graphite/conf/carbon.conf20161121-3157-l68z6k.lock
Error: /Stage[main]/Graphite::Config/File[/opt/graphite/conf/carbon.conf]/ensure: change from absent to file failed: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /opt/graphite/conf/carbon.conf20161121-3157-l68z6k.lock at 281:/etc/puppet/modules/graphite/manifests/config.pp
Error: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /opt/graphite/conf/storage-aggregation.conf20161121-3157-1djckiv.lock at 281:/etc/puppet/modules/graphite/manifests/config.pp
Error: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /opt/graphite/conf/storage-aggregation.conf20161121-3157-1djckiv.lock at 281:/etc/puppet/modules/graphite/manifests/config.pp
Wrapped exception:
No such file or directory @ dir_s_rmdir - /opt/graphite/conf/storage-aggregation.conf20161121-3157-1djckiv.lock
Error: /Stage[main]/Graphite::Config/File[/opt/graphite/conf/storage-aggregation.conf]/ensure: change from absent to file failed: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /opt/graphite/conf/storage-aggregation.conf20161121-3157-1djckiv.lock at 281:/etc/puppet/modules/graphite/manifests/config.pp
Error: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /opt/graphite/webapp/graphite/local_settings.py20161121-3157-l7k6xr.lock at 195:/etc/puppet/modules/graphite/manifests/config.pp
Error: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /opt/graphite/webapp/graphite/local_settings.py20161121-3157-l7k6xr.lock at 195:/etc/puppet/modules/graphite/manifests/config.pp
Wrapped exception:
No such file or directory @ dir_s_rmdir - /opt/graphite/webapp/graphite/local_settings.py20161121-3157-l7k6xr.lock
Error: /Stage[main]/Graphite::Config/File[/opt/graphite/webapp/graphite/local_settings.py]/ensure: change from absent to file failed: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /opt/graphite/webapp/graphite/local_settings.py20161121-3157-l7k6xr.lock at 195:/etc/puppet/modules/graphite/manifests/config.pp
Notice: /Stage[main]/Graphite::Config/Exec[Initial django db creation]: Dependency File[/opt/graphite/webapp/graphite/local_settings.py] has failures: true
Warning: /Stage[main]/Graphite::Config/Exec[Initial django db creation]: Skipping because of failed dependencies
Error: /Stage[main]/Graphite::Config/Exec[Initial django db creation]: Failed to call refresh: Working directory '/opt/graphite/webapp/graphite' does not exist
Error: /Stage[main]/Graphite::Config/Exec[Initial django db creation]: Working directory '/opt/graphite/webapp/graphite' does not exist
Notice: /Stage[main]/Graphite::Config/File[/opt/graphite/bin]: Dependency File[/opt/graphite/webapp/graphite/local_settings.py] has failures: true
Warning: /Stage[main]/Graphite::Config/File[/opt/graphite/bin]: Skipping because of failed dependencies
Notice: /Stage[main]/Graphite::Config/File[/var/lib/graphite-web]: Dependency File[/opt/graphite/webapp/graphite/local_settings.py] has failures: true
Warning: /Stage[main]/Graphite::Config/File[/var/lib/graphite-web]: Skipping because of failed dependencies
Notice: /Stage[main]/Graphite::Config/File[/opt/graphite/webapp/graphite/graphite_wsgi.py]: Dependency File[/opt/graphite/conf/graphite_wsgi.py] has failures: true
Warning: /Stage[main]/Graphite::Config/File[/opt/graphite/webapp/graphite/graphite_wsgi.py]: Skipping because of failed dependencies
Error: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /opt/graphite/conf/whitelist.conf20161121-3157-92267g.lock at 281:/etc/puppet/modules/graphite/manifests/config.pp
Error: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /opt/graphite/conf/whitelist.conf20161121-3157-92267g.lock at 281:/etc/puppet/modules/graphite/manifests/config.pp
Wrapped exception:
No such file or directory @ dir_s_rmdir - /opt/graphite/conf/whitelist.conf20161121-3157-92267g.lock
Error: /Stage[main]/Graphite::Config/File[/opt/graphite/conf/whitelist.conf]/ensure: change from absent to file failed: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /opt/graphite/conf/whitelist.conf20161121-3157-92267g.lock at 281:/etc/puppet/modules/graphite/manifests/config.pp
Notice: /Stage[main]/Graphite::Config/File[/opt/graphite/bin/carbon-logrotate.sh]: Dependency File[/opt/graphite/webapp/graphite/local_settings.py] has failures: true
Warning: /Stage[main]/Graphite::Config/File[/opt/graphite/bin/carbon-logrotate.sh]: Skipping because of failed dependencies
Notice: /Stage[main]/Graphite::Config/Cron[Rotate carbon logs]: Dependency File[/opt/graphite/webapp/graphite/local_settings.py] has failures: true
Warning: /Stage[main]/Graphite::Config/Cron[Rotate carbon logs]: Skipping because of failed dependencies
Notice: /Stage[main]/Graphite::Config/File[/opt/graphite/storage]: Dependency File[/opt/graphite/webapp/graphite/local_settings.py] has failures: true
Warning: /Stage[main]/Graphite::Config/File[/opt/graphite/storage]: Skipping because of failed dependencies
Notice: /Stage[main]/Graphite::Config/File[/opt/graphite/storage/whisper]: Dependency File[/opt/graphite/webapp/graphite/local_settings.py] has failures: true
Warning: /Stage[main]/Graphite::Config/File[/opt/graphite/storage/whisper]: Skipping because of failed dependencies
Notice: /Stage[main]/Graphite::Config/File[/opt/graphite/storage/rrd]: Dependency File[/opt/graphite/webapp/graphite/local_settings.py] has failures: true
Warning: /Stage[main]/Graphite::Config/File[/opt/graphite/storage/rrd]: Skipping because of failed dependencies
Notice: /Stage[main]/Graphite::Config/File[/opt/graphite/storage/lists]: Dependency File[/opt/graphite/webapp/graphite/local_settings.py] has failures: true
Warning: /Stage[main]/Graphite::Config/File[/opt/graphite/storage/lists]: Skipping because of failed dependencies
Notice: /Stage[main]/Graphite::Config/File[/opt/graphite/storage/graphite.db]: Dependency File[/opt/graphite/webapp/graphite/local_settings.py] has failures: true
Warning: /Stage[main]/Graphite::Config/File[/opt/graphite/storage/graphite.db]: Skipping because of failed dependencies
Notice: /Stage[main]/Graphite::Config/File[/opt/graphite/storage/log]: Dependency File[/opt/graphite/webapp/graphite/local_settings.py] has failures: true
Warning: /Stage[main]/Graphite::Config/File[/opt/graphite/storage/log]: Skipping because of failed dependencies
Notice: /Stage[main]/Graphite::Config/File[/opt/graphite/storage/log/carbon-cache]: Dependency File[/opt/graphite/webapp/graphite/local_settings.py] has failures: true
Warning: /Stage[main]/Graphite::Config/File[/opt/graphite/storage/log/carbon-cache]: Skipping because of failed dependencies
Notice: /Stage[main]/Graphite::Config_apache/Exec[fix graphite race condition]: Dependency File[/opt/graphite/webapp/graphite/local_settings.py] has failures: true
Warning: /Stage[main]/Graphite::Config_apache/Exec[fix graphite race condition]: Skipping because of failed dependencies
Notice: /Stage[main]/Graphite::Config/File[/etc/init.d/carbon-cache]: Dependency File[/opt/graphite/conf/carbon.conf] has failures: true
Warning: /Stage[main]/Graphite::Config/File[/etc/init.d/carbon-cache]: Skipping because of failed dependencies
Notice: /Stage[main]/Graphite::Config/Exec[graphite-reload-systemd]: Dependency File[/opt/graphite/conf/carbon.conf] has failures: true
Warning: /Stage[main]/Graphite::Config/Exec[graphite-reload-systemd]: Skipping because of failed dependencies
Notice: /Stage[main]/Graphite::Config/Exec[graphite-reload-systemd]: Triggered 'refresh' from 1 events
Notice: /Stage[main]/Graphite::Config/Service[carbon-cache]: Dependency File[/opt/graphite/conf/storage-schemas.conf] has failures: true
Notice: /Stage[main]/Graphite::Config/Service[carbon-cache]: Dependency File[/opt/graphite/conf/carbon.conf] has failures: true
Warning: /Stage[main]/Graphite::Config/Service[carbon-cache]: Skipping because of failed dependencies
Notice: /Stage[main]/Graphite::Config/Service[carbon-cache]: Triggered 'refresh' from 1 events
Notice: /Stage[main]/Graphite::Config_apache/Package[libapache2-mod-wsgi]/ensure: ensure changed 'purged' to 'present'
Notice: /Stage[main]/Graphite::Config_apache/File[/etc/apache2/ports.conf]: Dependency File[/opt/graphite/webapp/graphite/local_settings.py] has failures: true
Warning: /Stage[main]/Graphite::Config_apache/File[/etc/apache2/ports.conf]: Skipping because of failed dependencies
Notice: /Stage[main]/Graphite::Config_apache/File[/etc/apache2/sites-available/graphite.conf]: Dependency File[/opt/graphite/webapp/graphite/local_settings.py] has failures: true
Warning: /Stage[main]/Graphite::Config_apache/File[/etc/apache2/sites-available/graphite.conf]: Skipping because of failed dependencies
Notice: /Stage[main]/Graphite::Config_apache/File[/etc/apache2/sites-enabled/graphite.conf]: Dependency File[/opt/graphite/webapp/graphite/local_settings.py] has failures: true
Warning: /Stage[main]/Graphite::Config_apache/File[/etc/apache2/sites-enabled/graphite.conf]: Skipping because of failed dependencies
Notice: /Stage[main]/Graphite::Config_apache/Exec[Disable default apache site]/returns: executed successfully
Info: /Stage[main]/Graphite::Config_apache/Exec[Disable default apache site]: Scheduling refresh of Service[apache2]
Notice: /Stage[main]/Graphite::Config_apache/Service[apache2]: Dependency File[/opt/graphite/webapp/graphite/local_settings.py] has failures: true
Notice: /Stage[main]/Graphite::Config_apache/Service[apache2]: Dependency File[/opt/graphite/conf/graphite_wsgi.py] has failures: true
Warning: /Stage[main]/Graphite::Config_apache/Service[apache2]: Skipping because of failed dependencies
Notice: /Stage[main]/Graphite::Config_apache/Service[apache2]: Triggered 'refresh' from 1 events
Error: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /opt/graphite/conf/blacklist.conf20161121-3157-1x0nxnl.lock at 281:/etc/puppet/modules/graphite/manifests/config.pp
Error: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /opt/graphite/conf/blacklist.conf20161121-3157-1x0nxnl.lock at 281:/etc/puppet/modules/graphite/manifests/config.pp
Wrapped exception:
No such file or directory @ dir_s_rmdir - /opt/graphite/conf/blacklist.conf20161121-3157-1x0nxnl.lock
Error: /Stage[main]/Graphite::Config/File[/opt/graphite/conf/blacklist.conf]/ensure: change from absent to file failed: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /opt/graphite/conf/blacklist.conf20161121-3157-1x0nxnl.lock at 281:/etc/puppet/modules/graphite/manifests/config.pp
Notice: /Stage[main]/Graphite/Anchor[graphite::end]: Dependency File[/opt/graphite/conf/carbon.conf] has failures: true
Notice: /Stage[main]/Graphite/Anchor[graphite::end]: Dependency File[/opt/graphite/webapp/graphite/local_settings.py] has failures: true
Notice: /Stage[main]/Graphite/Anchor[graphite::end]: Dependency File[/opt/graphite/conf/graphite_wsgi.py] has failures: true
Notice: /Stage[main]/Graphite/Anchor[graphite::end]: Dependency File[/opt/graphite/conf/storage-schemas.conf] has failures: true
Notice: /Stage[main]/Graphite/Anchor[graphite::end]: Dependency File[/opt/graphite/conf/storage-aggregation.conf] has failures: true
Notice: /Stage[main]/Graphite/Anchor[graphite::end]: Dependency File[/opt/graphite/conf/whitelist.conf] has failures: true
Notice: /Stage[main]/Graphite/Anchor[graphite::end]: Dependency File[/opt/graphite/conf/blacklist.conf] has failures: true
Warning: /Stage[main]/Graphite/Anchor[graphite::end]: Skipping because of failed dependencies
Info: Creating state file /var/lib/puppet/state/state.yaml
Notice: Finished catalog run in 96.32 seconds
```

**Comment by GhostLyrics** [comment]
I am not sure how you would try to make this work with the stock `pip`. The issue is that if the program uses `wheel`s (the newer package format), they don't seem to respect some parameters, especially in regard to installation locations.

We might have to try and suppress usage of `wheel`s for all `pip` installed packages. I tried this via Puppet's `install_options` but did not have enough time to try different parameters to see if one of them might make it work. Also, I was not entirely sure for which of the Python packages this is needed - whether to do it for all of them or just some selected ones.

**Comment by Ajedi32** [comment]
See graphite-project/graphite-web#1508

According to that, we should pass `--no-binary=:all:` when installing Graphite. Note that `install_options` only works with the `pip` provider as of Puppet 4.1: https://tickets.puppetlabs.com/browse/PUP-4198

**Comment by GhostLyrics** [comment]
Will do.

I wasn't aware that 4.1 is required when combining `pip` and `install_options`. Explains why it did not work in my test.

**Comment by dwerder** [comment]
This can be a problem. Because setting the required puppet version to >4.1 would make that module useless for the majority of the puppet users I guess. Almost all distribution providing the puppet stable branch 3.8

**Comment by Ajedi32** [comment]
Well we really only need `install_options` on Xenial at the moment, but even Xenial provides only Puppet 3.8 in its package repositories.

The other option (the one I currently have working in my dev environment) is to downgrade pip to `6.1.1`, but that's a really awkward workaround, especially given that the version of pip in Xenial's package repositories has [a bug](https://bugs.launchpad.net/ubuntu/+source/salt/+bug/1586381) which makes simply downgrading with `sudo pip install pip==6.1.1` impossible.

Not sure if installing from a tarball instead of from PyPI fixes the problem (as suggested in graphite-project/graphite-web#1508). I'm going to give that a try a bit later...

**Comment by Ajedi32** [comment]
Okay, so I finally got around to experimenting with installing from a tarball. Turns out you _can_ fix the problem that way, but only if you give the tarball a name which does _not_ include at least one of the following characters: `g`, `r`, `a`, `p`, `h`, `i`, `t`, `e`, `-`, `w`, `b`.

If the tarball has a name which includes all of those characters (in any order), the package will get installed to the wrong location, otherwise it works fine. (Yes, seriously. I even [tested this](https://github.com/graphite-project/graphite-web/issues/1508#issuecomment-282814400).)

**Comment by Ajedi32** [comment]
At this point, I'm thinking that despite lack of support for Puppet 4.1 in Xenial it might be best to just go with the `install_options` method anyway and just require that people install Puppet 4.1 before using this module on Xenial. Every other possible workaround seems to require ridiculously terrible hacks.

**Comment by GhostLyrics** [comment]
You'll have to be aware though that as far as I remember using Puppet 4+ may also require extensive rewrite of existing code since the Puppet language changed.

**Comment by Ajedi32** [comment]
@GhostLyrics I've been testing this PR in an Ubuntu VM with Puppet 4.8 for a while now, so at least for Ubuntu I don't believe it'll be a problem.

**Comment by Ajedi32** [comment]
This is now ready to merge as far as I'm concerned. As stated in the description it won't work with the version of Puppet that ships with Ubuntu Xenial's package repos, but unfortunately there doesn't seem to be any good way around that. It works with Puppet 4.1+ which is good enough for me.

Note that I have only tested this on Ubuntu Xenial with Puppet 4.8. This PR _shouldn't_ change any behavior on non Ubuntu Xenial systems (e.g. it should still work fine with Puppet 3.8 on those systems), and all the tests still pass, but you might want to test it on another previously working system just to be sure.

Please let me know if you require me to make any additional changes to get this merged.

**Comment by dwerder** [comment]
That looks fine. Can you please update the README.md. There should be a info at the "Limitations"/"Campatibility Notes"

**Comment by Ajedi32** [comment]
Got it.

**Pull request merged**
