### PR TITLE
Small fixes and improvements

### PR DESCRIPTION
**Pull request by squarebracket**
This PR contains some bugfixes and some improvements.
- Remove obsolete `wsgi.py` link created in `config_gunicorn.pp`. It is no longer needed due to links made in `config.pp`. The template files have all been changed (in a previous PR) to match the new file.
- Removing gunicorn service subscription to `$local_setting_py_file`. The subscription was part of a PR I made that also moved the the variable definition above the include. Without this, puppet fails due to the resource `File[undef]` not existing.
- Change in variable used for `WorkingDirectory` in `templates/etc/systemd/gunicorn.service.erb` includes `/graphite` suffix -- removing hardcoded suffix.
- Make race condition fix script run only on initial install.
- Systemd bump now only happens on initial install.
- Added `service_provider` for Debian-based OSs in `params.pp`.
- Set explicit `provider` on gunicorn service (needed for Ubuntu 15.10).
- Set RedHat `service_provider` in `params.pp` rather than using OS version checks elsewhere in code.

### CODE REVIEW

**Comment by squarebracket** [comment]
Oi. What OS failed?

**Comment by dwerder** [comment]
You have to fix some checks. 

/spec/classes/graphite_config_spec.rb:59   The provider has to be changed to systemd now.

Furthermore the Debian/Ubuntu tests must be different for debians with and without systemd now.

**Comment by dwerder** [comment]
You can take a look at the failed checks here: https://travis-ci.org/echocat/puppet-graphite/builds/125648434 or by clicking on "Details" beneath the Failed checks warning.

**Comment by dwerder** [comment]
Beside the fixes of the spec tests, everything looks fine.

**Comment by squarebracket** [comment]
Ah, of course. I'll align the specs with code and push another commit.

**Comment by squarebracket** [comment]
Ok, fixed up all the specs. Also added a `config_gunicorn` spec. I'm still a pretty big noob to rspec, so if you have any suggestions on improvements, I'd be happy to hear them!

**Comment by dwerder** [comment]
Thanks a lot. Great PR.

**Pull request merged**
