### PR TITLE
Added check to validate Apache ports are integers

### PR DESCRIPTION
**Pull request by abednarik**
This is related to Issue #212

### CODE REVIEW

**Comment by dwerder** [comment]
Thanks for the commit, but it will fail, because we have a minimum dependency to stdlib 3.2.0 and the function validate_integer was first introduced at version 4.6.0. So we have to raise this dependency in metadata.json and .fixtures.yml. Raising this version is simple and should be done with a "major" release. So no one with "old" installation get into trouble.

**Comment by abednarik** [comment]
Got it.  I can do thjat for you, if you want. Just le me know. I'm using this module :)

**Comment by abednarik** [comment]
Now should be working fine and test should be Ok.

BTW I didn't update module version, since you are the owner :)

**Comment by dwerder** [comment]
Thanks. Now we will close that PR and reopen it against the develop branch as described in DEVELOP.md ;)

**Comment by abednarik** [comment]
Thanks :)  Will do

**Pull request closed without merging**
