### PR TITLE
python-crypto obsoleted by python2-crypto on RHEL/CentOS 7.x

### PR DESCRIPTION
**Pull request by madAndroid**
- addresses #243

### CODE REVIEW

**Comment by dwerder** [comment]
Please reopen agains develop branch. ;-) Thanks

**Comment by madAndroid** [comment]
sure :)

**Comment by madAndroid** [comment]
Done :) - #247

**Comment by dwerder** [comment]
This PR would mean, that EPEL is mandatory for this module.

**Pull request closed without merging**
