### PR TITLE
Using puppetlabs/apache module

### PR DESCRIPTION
**Pull request by sijis**
Here's a quick stab at converting to use puppetlabs/apache module. I did this prior to knowing about issue #78 

I know it worked against the 'master' branch on CentOS 6.x and i sync it against the v6.0.0 branch, leaving all the python virtualenv stuff intact.

I am getting an error though, so i cannot fully validate it. The error seems related to a missing graphite.db file, so syncdb is failing.
```
Error: /Stage[main]/Graphite::Config/Exec[Initial django db creation]: Failed to call refresh: echo $PATH; python manage.py syncdb --noinput returned 1 instead of one of [0]
Error: /Stage[main]/Graphite::Config/Exec[Initial django db creation]: echo $PATH; python manage.py syncdb --noinput returned 1 instead of one of [0]
```
Anyhow, i'd appreciate any feedback.

Sijis

### CODE REVIEW

**Comment by dwerder** [comment]
Thanks for the PR. It looks good. I will test it tomorrow to see it I can reproduce your error.

**Comment by dwerder** [comment]
@sijis I merged this PR, but this PR ignores a lot of logic hidden in the original apache template `templates/etc/apache2/sies-available/graphite.conf.erb`
Also if someone already includes apache class, because there are more webservices on the machine besides graphite, he will run into conflicts. Not to mention differences between apache 2.2 and 2.4 and ssl configs.

This brings me to the point, that I will just drop all that built-in Apache support and instead give an README example how to configure things with separate modules.

Like
```
class { apache: }
apache::vhost {foo bar}
class {graphite: }

Class[apache]->Class[graphite]
```

**Comment by sijis** [comment]
My test setup was fairly vanilla so I didnt look at the intricate details
of the existing apache template. I did have in mind to add SSL support
parts though.

It does make better sense to keep apache out and just include examples.
Someone could easily wrap both modules in a custom one to keep paths
consistent.

At least this brought up a good revelation though.

Sijis

**Comment by everestx** [comment]
I agree that keeping a simple option for configuring apache and also the option to manage externally is a good way to go.

**Pull request merged**
