### PR TITLE
[develop] python-crypto obsoleted by python2-crypto on RHEL / CentOS 7

### PR DESCRIPTION
**Pull request by madAndroid**
addresses #243

### CODE REVIEW

**Comment by dwerder** [comment]
This PR would mean, that EPEL is mandatory for this module.

**Comment by madAndroid** [comment]
hmm.. yes, that's a tricky one - any suggestions on how to get around that?

**Comment by dwerder** [comment]
Ok, it is no real problem, because EPEL is mandatory already. We need it for package `python-tzlocal`.

**Comment by madAndroid** [comment]
Awesome, thanks! :)

**Pull request merged**
