### PR TITLE
Service definitions should be in their own namespace

### PR DESCRIPTION
**Pull request by alexxxxx**
Signed-off-by: Alexandre Beche alexandre.beche@gmail.com

### CODE REVIEW

**Comment by dwerder** [comment]
The PR is ok and I can live with it. But can you please fix the CI?

**Comment by alexxxxx** [comment]
I'm not sure what this failures are, I'll have a look, was develop branch clean before my changes?
Side questions, why install and config class inherit from params and not the graphite one?

**Comment by dwerder** [comment]
1. The CI was green before.
2. Legacy code. Long time ago there might be a reason for that ;)

**Comment by dwerder** [comment]
But puppetlabs himself recommend to inherit only classes light params.pp and avoid everything else and work withc "include" and "contain" instead.

**Pull request closed without merging**
